language: python
python:
  - "3.9"
env:
  - DATABASE_NAME=test_db
  - DATABASE_USER=postgres
  - DATABASE_PASSWORD=''
  - DATABASE_HOST=localhost
services:
  - postgresql
before_install: cd bc_full_stack_developer
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - python manage.py test